--- # insall httpd server
- hosts: groupname
  remtoe_user: username
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: install httpd server
    yum:
      name: httpd
      state: present
    notify:
     - start service    
  handlers:
  - name: start service
    service:
      name: httpd
      state: restarted
      enabled: yes
